-- Study Shield backend database bootstrap.
-- Runs on every startup before Hibernate's ddl-auto update (spring.sql.init.mode: always).
--
-- Two environments share one Postgres database, one schema each:
--   * default profile -> "ss-dev"   (development)
--   * 'prod' profile  -> "ss-prod"  (production)
--
-- This script is profile-independent: it creates BOTH schemas and applies the
-- same idempotent column backfills to both, so the two environments stay in
-- lock-step no matter which profile starts first.

CREATE SCHEMA IF NOT EXISTS "ss-dev";
CREATE SCHEMA IF NOT EXISTS "ss-prod";

-- Backfill display_order on existing subjects tables. This runs before Hibernate's
-- ddl-auto update, which would otherwise fail with a NOT NULL ADD COLUMN on a table
-- that already has rows. Idempotent: no-ops when subjects is absent (fresh DB) or when
-- the column already exists.
ALTER TABLE IF EXISTS "ss-dev".subjects  ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS "ss-prod".subjects ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 0;

-- Two user types: MOBILE (mobile/tv app accounts) and ADMIN (admin app accounts).
-- Idempotent: adds the column once; backfills existing ADMIN-role rows so they stay
-- admins even though the column default is MOBILE. Hibernate then picks up the column
-- via ddl-auto update.
-- The whole block is guarded by table existence: this script runs BEFORE Hibernate's
-- ddl-auto (spring.sql.init default ordering), so on a fresh database the tables do not
-- exist yet and there is nothing to backfill. ALTER ... IF EXISTS is safe by itself,
-- but the UPDATEs would fail on a missing table, so they only run when the table is there.
-- Written as DO '<text>' (not DO $$...$$) because Spring's ScriptUtils parser does not
-- understand dollar quoting.
DO 'BEGIN
    IF to_regclass(''"ss-dev".users'') IS NOT NULL THEN
        ALTER TABLE "ss-dev".users ADD COLUMN IF NOT EXISTS user_type varchar(16) NOT NULL DEFAULT ''MOBILE'';
        UPDATE "ss-dev".users SET user_type = ''ADMIN'' WHERE role = ''ADMIN'' AND user_type <> ''ADMIN'';
    END IF;
    IF to_regclass(''"ss-prod".users'') IS NOT NULL THEN
        ALTER TABLE "ss-prod".users ADD COLUMN IF NOT EXISTS user_type varchar(16) NOT NULL DEFAULT ''MOBILE'';
        UPDATE "ss-prod".users SET user_type = ''ADMIN'' WHERE role = ''ADMIN'' AND user_type <> ''ADMIN'';
    END IF;
END';

-- Question versioning: every version of a question shares a version_group_id and carries an
-- ascending version_number. A row whose superseded_by_id is NULL is the latest version for its
-- quiz ("always use the latest version of a question for a quiz"). Idempotent: adds the columns
-- once so Hibernate's ddl-auto update can pick them up on existing DBs.
ALTER TABLE IF EXISTS "ss-dev".questions  ADD COLUMN IF NOT EXISTS version_group_id varchar(64);
ALTER TABLE IF EXISTS "ss-dev".questions  ADD COLUMN IF NOT EXISTS version_number integer NOT NULL DEFAULT 1;
ALTER TABLE IF EXISTS "ss-prod".questions ADD COLUMN IF NOT EXISTS version_group_id varchar(64);
ALTER TABLE IF EXISTS "ss-prod".questions ADD COLUMN IF NOT EXISTS version_number integer NOT NULL DEFAULT 1;

-- Relax subjects.class_grade_id to nullable (global subjects have no class grade).
-- Idempotent: only alters when the table/column exists AND is currently NOT NULL.
DO 'BEGIN
    IF to_regclass(''"ss-dev".subjects'') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = ''ss-dev'' AND table_name = ''subjects'' AND column_name = ''class_grade_id'' AND is_nullable = ''NO'') THEN
        ALTER TABLE "ss-dev".subjects ALTER COLUMN class_grade_id DROP NOT NULL;
    END IF;
    IF to_regclass(''"ss-prod".subjects'') IS NOT NULL AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = ''ss-prod'' AND table_name = ''subjects'' AND column_name = ''class_grade_id'' AND is_nullable = ''NO'') THEN
        ALTER TABLE "ss-prod".subjects ALTER COLUMN class_grade_id DROP NOT NULL;
    END IF;
END';

-- Academic structure (Long model, matches JPA entities ClassLevel/BoardClass/Offering).
-- boards/subjects tables are NOT declared here: they already exist via Hibernate
-- ddl-auto (Board.java, Subject.java). No Country entity exists, so no countries table.
-- Fresh DBs: schema.sql runs BEFORE Hibernate creates boards/subjects, so the tables
-- below are created WITHOUT FK constraints; FKs/uniques are added idempotently via
-- guarded DO blocks once the referenced tables exist. BOTH schemas stay in lock-step.
CREATE TABLE IF NOT EXISTS "ss-dev".class_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordinal integer NOT NULL,
    slug varchar(255) NOT NULL,
    canonical_name varchar(255) NOT NULL,
    age_min_years double precision,
    age_max_years double precision,
    stage varchar(64),
    notes varchar(1024)
);
CREATE TABLE IF NOT EXISTS "ss-prod".class_levels (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordinal integer NOT NULL,
    slug varchar(255) NOT NULL,
    canonical_name varchar(255) NOT NULL,
    age_min_years double precision,
    age_max_years double precision,
    stage varchar(64),
    notes varchar(1024)
);
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS ordinal integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS slug varchar(255);
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS canonical_name varchar(255);
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS age_min_years double precision;
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS age_max_years double precision;
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS stage varchar(64);
ALTER TABLE IF EXISTS "ss-dev".class_levels  ADD COLUMN IF NOT EXISTS notes varchar(1024);
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS ordinal integer NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS slug varchar(255);
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS canonical_name varchar(255);
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS age_min_years double precision;
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS age_max_years double precision;
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS stage varchar(64);
ALTER TABLE IF EXISTS "ss-prod".class_levels ADD COLUMN IF NOT EXISTS notes varchar(1024);
CREATE UNIQUE INDEX IF NOT EXISTS uq_class_levels_ordinal ON "ss-dev".class_levels(ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_class_levels_slug ON "ss-dev".class_levels(slug);
CREATE UNIQUE INDEX IF NOT EXISTS uq_class_levels_ordinal ON "ss-prod".class_levels(ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_class_levels_slug ON "ss-prod".class_levels(slug);

CREATE TABLE IF NOT EXISTS "ss-dev".board_class (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint NOT NULL,
    class_level_id bigint NOT NULL,
    display_name varchar(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS "ss-prod".board_class (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint NOT NULL,
    class_level_id bigint NOT NULL,
    display_name varchar(255) NOT NULL
);
ALTER TABLE IF EXISTS "ss-dev".board_class  ADD COLUMN IF NOT EXISTS board_id bigint;
ALTER TABLE IF EXISTS "ss-dev".board_class  ADD COLUMN IF NOT EXISTS class_level_id bigint;
ALTER TABLE IF EXISTS "ss-dev".board_class  ADD COLUMN IF NOT EXISTS display_name varchar(255);
ALTER TABLE IF EXISTS "ss-prod".board_class ADD COLUMN IF NOT EXISTS board_id bigint;
ALTER TABLE IF EXISTS "ss-prod".board_class ADD COLUMN IF NOT EXISTS class_level_id bigint;
ALTER TABLE IF EXISTS "ss-prod".board_class ADD COLUMN IF NOT EXISTS display_name varchar(255);
CREATE UNIQUE INDEX IF NOT EXISTS uq_board_class_board_level ON "ss-dev".board_class(board_id, class_level_id);
DROP INDEX IF EXISTS "ss-dev".uq_board_class_board_name;
CREATE UNIQUE INDEX IF NOT EXISTS uq_board_class_board_level ON "ss-prod".board_class(board_id, class_level_id);
DROP INDEX IF EXISTS "ss-prod".uq_board_class_board_name;
-- Hibernate (ddl-auto:update) never drops constraints, so remove any leftover unique
-- constraint on board_class(display_name) regardless of its generated name
-- (your matrix legitimately repeats labels: ENG Nursery twice, US Preschool twice).
DO 'DECLARE r record;
BEGIN
    FOR r IN SELECT conname, n.nspname AS schemaname
             FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace
             JOIN pg_class t ON t.oid = c.conrelid
             WHERE t.relname = ''board_class''
               AND (n.nspname = ''ss-dev'' OR n.nspname = ''ss-prod'')
               AND c.contype = ''u''
               AND pg_get_constraintdef(c.oid) LIKE ''%display_name%''
    LOOP
        EXECUTE format(''ALTER TABLE %I.board_class DROP CONSTRAINT %I'', r.schemaname, r.conname);
    END LOOP;
END';

CREATE TABLE IF NOT EXISTS "ss-dev".board_class_subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_class_id bigint NOT NULL,
    subject_id bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "ss-prod".board_class_subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_class_id bigint NOT NULL,
    subject_id bigint NOT NULL
);
ALTER TABLE IF EXISTS "ss-dev".board_class_subject  ADD COLUMN IF NOT EXISTS board_class_id bigint;
ALTER TABLE IF EXISTS "ss-dev".board_class_subject  ADD COLUMN IF NOT EXISTS subject_id bigint;
ALTER TABLE IF EXISTS "ss-prod".board_class_subject ADD COLUMN IF NOT EXISTS board_class_id bigint;
ALTER TABLE IF EXISTS "ss-prod".board_class_subject ADD COLUMN IF NOT EXISTS subject_id bigint;
CREATE UNIQUE INDEX IF NOT EXISTS uq_offering_bc_subject ON "ss-dev".board_class_subject(board_class_id, subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_offering_bc_subject ON "ss-prod".board_class_subject(board_class_id, subject_id);

-- ContentPack/Quiz offering association (admin app lists by offering).
-- Idempotent: adds nullable BIGINT columns once; Hibernate ddl-auto picks them up.
ALTER TABLE IF EXISTS "ss-dev".content_packs  ADD COLUMN IF NOT EXISTS offering_id bigint;
ALTER TABLE IF EXISTS "ss-prod".content_packs ADD COLUMN IF NOT EXISTS offering_id bigint;
ALTER TABLE IF EXISTS "ss-dev".quizzes  ADD COLUMN IF NOT EXISTS offering_id bigint;
ALTER TABLE IF EXISTS "ss-prod".quizzes ADD COLUMN IF NOT EXISTS offering_id bigint;

-- FKs to Hibernate-managed tables (boards, subjects, class_levels): only added when BOTH
-- tables exist, so fresh DBs (pre-ddl-auto) skip safely and existing DBs converge.
DO 'BEGIN
    IF to_regclass(''"ss-dev".board_class'') IS NOT NULL AND to_regclass(''"ss-dev".boards'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_board_class_board_dev'') THEN
        ALTER TABLE "ss-dev".board_class ADD CONSTRAINT fk_board_class_board_dev FOREIGN KEY (board_id) REFERENCES "ss-dev".boards(id);
    END IF;
    IF to_regclass(''"ss-dev".board_class'') IS NOT NULL AND to_regclass(''"ss-dev".class_levels'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_board_class_level_dev'') THEN
        ALTER TABLE "ss-dev".board_class ADD CONSTRAINT fk_board_class_level_dev FOREIGN KEY (class_level_id) REFERENCES "ss-dev".class_levels(id);
    END IF;
    IF to_regclass(''"ss-prod".board_class'') IS NOT NULL AND to_regclass(''"ss-prod".boards'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_board_class_board_prod'') THEN
        ALTER TABLE "ss-prod".board_class ADD CONSTRAINT fk_board_class_board_prod FOREIGN KEY (board_id) REFERENCES "ss-prod".boards(id);
    END IF;
    IF to_regclass(''"ss-prod".board_class'') IS NOT NULL AND to_regclass(''"ss-prod".class_levels'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_board_class_level_prod'') THEN
        ALTER TABLE "ss-prod".board_class ADD CONSTRAINT fk_board_class_level_prod FOREIGN KEY (class_level_id) REFERENCES "ss-prod".class_levels(id);
    END IF;
    IF to_regclass(''"ss-dev".board_class_subject'') IS NOT NULL AND to_regclass(''"ss-dev".board_class'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_offering_bc_dev'') THEN
        ALTER TABLE "ss-dev".board_class_subject ADD CONSTRAINT fk_offering_bc_dev FOREIGN KEY (board_class_id) REFERENCES "ss-dev".board_class(id);
    END IF;
    IF to_regclass(''"ss-dev".board_class_subject'') IS NOT NULL AND to_regclass(''"ss-dev".subjects'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_offering_subject_dev'') THEN
        ALTER TABLE "ss-dev".board_class_subject ADD CONSTRAINT fk_offering_subject_dev FOREIGN KEY (subject_id) REFERENCES "ss-dev".subjects(id);
    END IF;
    IF to_regclass(''"ss-prod".board_class_subject'') IS NOT NULL AND to_regclass(''"ss-prod".board_class'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_offering_bc_prod'') THEN
        ALTER TABLE "ss-prod".board_class_subject ADD CONSTRAINT fk_offering_bc_prod FOREIGN KEY (board_class_id) REFERENCES "ss-prod".board_class(id);
    END IF;
    IF to_regclass(''"ss-prod".board_class_subject'') IS NOT NULL AND to_regclass(''"ss-prod".subjects'') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = ''fk_offering_subject_prod'') THEN
        ALTER TABLE "ss-prod".board_class_subject ADD CONSTRAINT fk_offering_subject_prod FOREIGN KEY (subject_id) REFERENCES "ss-prod".subjects(id);
    END IF;
END';