spring:
  application:
    name: ss-api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/auth/**

        - id: content-service
          uri: ${services.content-service.url}
          predicates:
            - Path=/api/v1/boards/**, /api/v1/class-grades/**, /api/v1/subjects/**, /api/v1/content-packs/**, /api/v1/quizzes/**, /api/v1/questions/**, /api/v1/freemium/**

        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/v1/users/**, /api/v1/parents/**, /api/v1/children/**, /api/parents/**, /api/students/**

        - id: quiz-attempts
          uri: ${services.quiz-attempts.url}
          predicates:
            - Path=/api/v1/quiz-attempts/**, /api/v1/attempt-answers/**, /api/v1/quiz-results/**

        - id: tv-device-service
          uri: ${services.tv-device-service.url}
          predicates:
            - Path=/api/v1/wifi-networks/**, /api/v1/connected-tvs/**, /api/v1/tv-users/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    web-application-type: reactive

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway

services:
  content-service:
    url: https://ss-content-service.onrender.com
  user-service:
    url: https://ss-user-service.onrender.com
  quiz-attempts:
    url: https://ss-quiz-attempts.onrender.com
  tv-device-service:
    url: https://ss-tv-device-service.onrender.com
